### ISSUE TITLE
Change user password

### ISSUE THREAD

**Issue by rahimbtc** [OpenEx-Platform/openex#121]
Hello everyone;
I wonder how can i change password for a specific user ?

**Comment by SamuelHassine** [comment]
Hello @rahimbtc,

You have to go in the Settings -> Users, then you can click on the button "Update the password":

![image](https://user-images.githubusercontent.com/1334279/158404728-260bee7b-3b08-41b6-be4d-1bd903f1e8ef.png)

Kind regards,
Samuel

**Comment by SamuelHassine** [comment]
Hello,

@rahimbtc are you sure you're in the Settings -> Users section and not the "Players" section?

**Comment by rahimbtc** [comment]
Yes I'm sure sir

**Comment by SamuelHassine** [comment]
Hello,

@rahimbtc Do you still have the problem? The "Update password" button is only available if you are an administrator of the platform and is not available for the "Administrator" account which is locked by the configuration.

Kind regards,
Samuel

**Comment by SamuelHassine** [comment]
This should be solve in the latest release, and please make sure you are not trying to update the "admin" account. The password is in the static configuration.
