### ISSUE TITLE
Inject at T0 (+ 0 seconds) are not displayed in the timeline

### ISSUE THREAD

**Issue by SamuelHassine** [OpenEx-Platform/openex#257]
## Problem to Solve

Inject at T0 (+ 0 seconds) are not displayed in the timeline. 

Seems to be a CSS / HTML problem.

**Comment by guillaumejparis** [comment]
@SamuelHassine I tried to reproduce it but it seems to me that there is no problem, do you still reproduce ? (if yes please tell me browser and resolution as it is my best bet of solving it).

**Comment by RomuDeuxfois** [comment]
Not reproducible in latest version
