### ISSUE TITLE
Impossible to access a document / file when adding it to an inject before actual update

### ISSUE THREAD

**Issue by SamuelHassine** [OpenEx-Platform/openex#258]
## Description

When adding a document to an inject, it is essential to click on "Update" the inject before wanting accessing the document (for control for example). Otherwise, we get a 500 error from the server and the document is not added.

Very concretely, you should not try to see the file in PJ before having modified the stimuli

**Comment by guillaumejparis** [comment]
@SamuelHassine love to have a step by step to reproduce this one, because i don't really understand how you can access the document without update before.
 (I tested on an email inject in the scenario tab)

**Comment by SamuelHassine** [comment]
@guillaumejparis, please refer to https://filigran.atlassian.net/browse/OEX1-8.

**Comment by RomuDeuxfois** [comment]
Can be reproduce with a no admin user
