### ISSUE TITLE
Delete cascade from user to injects should never happen

### ISSUE THREAD

**Issue by SamuelHassine** [OpenEx-Platform/openex#272]
## Description

When deleting a user in the platform, all injects created by the user are deleted. We need a "set null" behavior on the creator....

**Comment by guillaumejparis** [comment]
I reproduce it.
I found what causes this (w Romuald), in our db schema we have a delete cascade constraint on the inject from the user : 

` inject_user                 varchar(255) default NULL::character varying
        constraint fk_a60839b2e20fc097
            references users
            on delete cascade,
            `
So to fix the problem we need to make a migration but before rush headfirst I prefer to ask you @richard-julien, do you remember if there is a good reason to have done that ?

**Comment by guillaumejparis** [comment]
Ok I checked all the others delete cascade for the user, they seem legit the only one that I have a doubt is the logs one : 
```
create table if not exists logs
(
    log_id       varchar(255)                not null
        constraint logs_pkey
            primary key,
    log_exercise varchar(255) default NULL::character varying
        constraint fk_f08fc65cc0891ec3
            references exercises
            on delete cascade,
    log_user     varchar(255) default NULL::character varying
        constraint fk_f08fc65c9cfd383c
            references users
            on delete cascade,
    log_title    varchar(255)                not null,
    log_content  text                        not null,
    log_date     timestamp(0) with time zone not null
); 
```
Not sure if we want to keep this kind of logs even when user is deleted

**Comment by RomuDeuxfois** [comment]
Agree, I am not sure this is useful to keep it
