### ISSUE TITLE
Creating a lesson in OpenEX sends me to login page

### ISSUE THREAD

**Issue by Majin-Jermain** [OpenEx-Platform/openex#298]
## Description

When I try to create a new "Lessons learned", OpenEX logs me out and takes me back to the login page.

## Environment

It's in the demo OpenEX environment at https://demo.openex.io/

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1) Navigate to the "Lessons learned" page,
2) Click on the "+" icon in the bottom right,
3) Enter data in the Name and Description fields of the pop up;
4) Click on "CREATE";

Then for me, the page reloads and I am taken back to the OpenEX login page. My session is closed and I have to enter my username and password again to continue using OpenEX.

## Expected Output

I expected a Lesson learned entry to be created.

## Actual Output

No lesson learned is created. I am logged out of my session.
 
## Screenshots (optional)

![OpenEx1](https://github.com/OpenEx-Platform/openex/assets/58041836/fd6c7855-8d66-4838-84e5-d263c5818a69)

![OpenEx2](https://github.com/OpenEx-Platform/openex/assets/58041836/0c5a0818-e36b-4a7d-9c1d-09141d5878df)

**Comment by guillaumejparis** [comment]
It is a rights problem, it is a contradiction between what the user see "create a new lesson" button and what he really has the right to do
