### ISSUE TITLE
Cannot create media pressure 

### ISSUE THREAD

**Issue by guillaumejparis** [OpenEx-Platform/openex#345]
Bug in one of our demo instance, did not find a reproducible scenario on local and other demo instances.
(maybe a bad cache update of the front)

**Comment by RomuDeuxfois** [comment]
@SamuelHassine, @Jipegien, @nino-filigran 

When we use the trigger now functionality, we have a negatif date on the inject based on the exercice starting date and this can lead to issues.
If I understand clearly the inject date behavior, when we user 'trigger now' we need to fill the inject date with this : now() - exercice starting date.

**Comment by RomuDeuxfois** [comment]
Need to keep a positif date.
This will fix this issue : https://github.com/OpenEx-Platform/openex/issues/257
![image](https://github.com/OpenEx-Platform/openex/assets/53513584/1f09ef67-f422-4606-8cd4-04641a5ea155)
