### ISSUE TITLE
Impossible to create a player

### ISSUE THREAD

**Issue by Lhorus6** [OpenEx-Platform/openex#405]
## Description

It's impossible to create a player. When you press the "Create" button, nothing happens.

## Environment

OpenEX 3.4.1-SNAPSHOT

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go on "Players"
2. Click on "+"
3. Fill in all the fields
4. Click on "CREATE"
5. -> Nothing happens

**Comment by RomuDeuxfois** [comment]
Duplicate of https://github.com/OpenEx-Platform/openex/issues/404
