### ISSUE TITLE
Links and documentation outdated - /api/tokens not found

### ISSUE THREAD

**Issue by J-i-x** [OpenEx-Platform/openex#57]
Hello,

I wanted to test this platform. Documentation and links seems to not work and are refering to OpenCTI, not Openex. Would it be possible to fix this issue by replacing the VM/Docker links ?

Even though I tried to download the elements and follow these instructions: https://www.openex.io/fr/documentation/

It seems that it does not work at all. I get through the process, app configured, worker started, but there is an issue while I am trying to connect through the web interface. It seems that /api/tokens does not exist... 

Any ideas?

I could help to fix the different issues I mentioned. But I need the right links and pointers.

Hope I will find someone to help me :)

**Comment by SamuelHassine** [comment]
Hello @J-i-x,

Thanks for opening an issue on that. We are working very very hard to release full refactored version (2.0.0) of OpenEx. The documentation will be updated as well as the website. We hope to be able to do everything in the next couple weeks. I will inform you here a few days before the release.

Kind regards,
Samuel
