### ISSUE TITLE
Add objective as selection option to incidents

### ISSUE THREAD

**Issue by Balura** [OpenEx-Platform/openex#70]
## Problem to Solve
While creating an incident, only subobjectives can be selected. Would also be good to have the possibility to select objectives, since subobjectives are optional.

## Current Workaround

Use subobjectives

## Proposed Solution

As with subobjectives also add objectives to the selection possibilites (see attachment) **preferred** or
make at least one subobjective mandatory for each object

## Additional Information

![image](https://user-images.githubusercontent.com/36966185/108033562-77799880-7034-11eb-8e4d-0b550397b244.png)

**Comment by SamuelHassine** [comment]
We will refactor the objectives / incidents in the next version. Related issue is #111.
