### ISSUE TITLE
Missing english translation for incident type

### ISSUE THREAD

**Issue by Balura** [OpenEx-Platform/openex#71]
## Description
For creating an incident and selecting the type, the english translation is missing. French words are used:
Technique, Opérationnel, Stratégique could translate to Technical, Operational and Strategic

## Environment

1. OS (where OpenEx server runs): Ubuntu 20.04
2. OpenEx version: OpenEx 2.0.0
3. OpenEx client: Frontend
4. Other environment details: Docker image: openexhq/platform:v2.0.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create event
2. Create incident
3. Select type

## Expected Output

English wording: Technical, Operational and Strategic

## Actual Output

French wording: Technique, Opérationnel, Stratégique
 
## Additional information
![image](https://user-images.githubusercontent.com/36966185/108034334-a6443e80-7035-11eb-8366-beb3e74e45ae.png)

**Comment by SamuelHassine** [comment]
Incidents will be removed in future version to this screen will not exist anymore.
