### ISSUE TITLE
Docker - DockerFile

### ISSUE THREAD

**Issue by b4b857f6ee** [OpenEx-Platform/openex#79]
## Problem to Solve

I'm looking to do a DockerFile :)

## Current Workaround

Trying to do it...

## Proposed Solution

Some guide or already Dockerfile :)

**Comment by SamuelHassine** [comment]
Hello,

Depending on what you need:

- `docker-compose.yml` is here: https://github.com/OpenEx-Platform/docker/blob/master/docker-compose.yml
- `Dockerfile` for the platform is here: https://github.com/OpenEx-Platform/openex/blob/master/openex-platform/Dockerfile
- `Dockerfile` for the player is here: https://github.com/OpenEx-Platform/openex/blob/master/openex-player/Dockerfile

Kind regards,
Samuel
