### ISSUE TITLE
I can't access to the openex dashboard

### ISSUE THREAD

**Issue by kl3pticK** [OpenEx-Platform/openex#90]
Hello Champions,
## Description
 When i try to run openex, either on VM import or docker, i can access to the portainer dashboard but the access to the app is impossible.
  On port 8000 i have a message : Not found.
  On port 8080 : Connection refused.

Here's a screenshot of the portainer images status : 

![image](https://user-images.githubusercontent.com/92788607/137888008-8b1aa000-e891-4174-88f8-2f4523168dcd.png)

and i can't see any stack on the stacks dashboard : 
![image](https://user-images.githubusercontent.com/92788607/137888191-55e33a34-08f1-4d62-b481-53ee03f0ac29.png)

## Environment

1. OS (where OpenEx server runs): VM OVF Import
2. OpenEx version:  2.0.0
3. OpenEx client: Chrome from Linux machine

## Expected Output

Access to the dashboard of openex
## Actual Output

nothing happening

**Comment by SamuelHassine** [comment]
Will be fixed in 3.0.0.
