### ISSUE TITLE
Add capabilities of having all exchanged emails in OpenEx

### ISSUE THREAD

**Issue by SamuelHassine** [OpenEx-Platform/openex#93]
## Problem to Solve

Add capabilities of having all exchanged emails in OpenEx and answer to emails within the UI.

## Current Workaround

None.

## Proposed Solution

Implement mail IMAP reader and direct email sending capabilities.

## Additional Information

None

**Comment by richard-julien** [comment]
Hi @VictorHugoLG , its currently under active development.
